configs:
  cm:
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"

global:
  image:
    tag: "v2.12.3"

crds:
  install: true
  keep: true

redis-ha:
  enabled: true

controller:
  replicas: 2

server:
  replicas: 2

applicationSet:
  replicas: 2

repoServer:
  env:
    - name: GNUPGHOME
      value: /gnupg-home/.gnupg
  replicas: 2
  initContainers:
    - name: import-gpg-key
      image: argoproj/argocd:v2.12.3
      command: [ "/usr/bin/bash", "-c" ]
      args:
        - for i in $( find /sops-gpg -maxdepth 2 -type f -printf "%p\n"); do gpg --import $i; done
      env:
        - name: GNUPGHOME
          value: /gnupg-home/.gnupg
      volumeMounts:
        - mountPath: /sops-gpg
          name: sops-gpg
        - mountPath: /gnupg-home
          name: gnupg-home
    - name: install-ksops
      image: danieles/elogic-ksops:0.0.1
      imagePullPolicy: Always
      command: ["/bin/sh", "-c"]
      args:
        - echo "Installing ESOPS...";
          mv /usr/local/bin/esops /custom-tools/;
          echo "Done.";
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: gnupg-home
      emptyDir: {}
    - name: sops-gpg
      secret:
        defaultMode: 420
        secretName: sops-gpg
  volumeMounts:
    - mountPath: /usr/local/bin/esops
      name: custom-tools
      subPath: esops
    - mountPath: /gnupg-home
      name: gnupg-home